ALTER TABLE "public"."Settingpoint"
ADD COLUMN IF NOT EXISTS "memberDiscountPercent" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN IF NOT EXISTS "memberDiscountEnabled" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "public"."Datalist"
ADD COLUMN IF NOT EXISTS "memberDiscountEligible" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "public"."SaleMain"
ADD COLUMN IF NOT EXISTS "memberDiscount" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS "memberDiscountPercent" DOUBLE PRECISION DEFAULT 0;

ALTER TABLE "public"."Sale"
ADD COLUMN IF NOT EXISTS "memberDiscount" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS "memberDiscountPercent" DOUBLE PRECISION DEFAULT 0;
