-- เพิ่มขนาดตัวอักษรแยกแต่ละบรรทัด (pt) ให้ตัวช่วยฉลากยา
ALTER TABLE "LabelHelper" ADD COLUMN "line1Size" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "LabelHelper" ADD COLUMN "line2Size" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "LabelHelper" ADD COLUMN "line3Size" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "LabelHelper" ADD COLUMN "line4Size" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "LabelHelper" ADD COLUMN "line5Size" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "LabelHelper" ADD COLUMN "line6Size" INTEGER NOT NULL DEFAULT 10;
